version: '3.1'

services:

  shop:
    container_name: shop
    build:
      context: services/shop
      dockerfile: Dockerfile-dev
    volumes:
      - './services/shop:/usr/src/app'
    ports:
      - 5001:5000
    environment:
      - FLASK_DEBUG=1
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/pis_dev
      - DATABASE_TEST_URL=postgresql://postgres:postgres@db:5432/pis_test
      - SECRET_KEY=my_precious
      - JWT_SECRET_KEY=super_secret
      - UPLOAD_FOLDER=../public/uploads
    depends_on:
      - db
    links:
      - db

  db:
    container_name: db
    build:
      context: services/db
      dockerfile: Dockerfile
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  nginx:
    container_name: nginx
    build:
      context: services/nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
    depends_on:
      - shop
