version: '3.1'

services:

  api:
    container_name: api
    build:
      context: services/api
      dockerfile: Dockerfile-prod
    expose:
      - '5000'
    environment:
      - APP_SETTINGS=project.config.ProductionConfig
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/pis_prod
      - DATABASE_TEST_URL=postgresql://postgres:postgres@db:5432/pis_test
    depends_on:
      - db
    links:
      - db

  db:
    container_name: db
    build:
      context: services/db
      dockerfile: Dockerfile
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  nginx:
    container_name: nginx
    build:
      context: services/nginx
      dockerfile: Dockerfile-prod
    restart: always
    ports:
      - 80:80
    depends_on:
      - api
      - client

  client:
    container_name: client
    build:
      context: ./services/client
      dockerfile: Dockerfile-prod
      args:
        - NODE_ENV=production
        - REACT_APP_API_SERVICE_URL=${REACT_APP_API_SERVICE_URL}
    ports:
      - '3007:80'
    depends_on:
      - api
    links:
      - api
